-- select 문 연습
-- 자바 연습하기 싫은 날이나 바쁜 날 sql 하나씩하는데 오늘 혈압오름

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE(DATE_OF_BIRTH) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03'
ORDER BY MEMBER_ID ASC;

-- 오라클
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
ORDER BY MEMBER_ID ASC;

-- 뒤에 계속 타임스탬프가 같이 딸려나온다...
-- 방법은...
-- 1. DATE_FORMAT()함수 사용
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND MONTH(DATE_OF_BIRTH) = 3
ORDER BY MEMBER_ID ASC;

-- 2. CAST() 또는 CONVERT() 사용
SELECT MEMBER_ID, MEMBER_NAME, GENDER, CAST(DATE_OF_BIRTH AS DATE) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND MONTH(DATE_OF_BIRTH) = 3
ORDER BY MEMBER_ID ASC;

-- 3. LEFT() 함수 사용
SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH, 10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND MONTH(DATE_OF_BIRTH) = 3
ORDER BY MEMBER_ID ASC;

-- 오라클
-- 1. TO_CHAR()함수 사용
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
ORDER BY MEMBER_ID ASC;

-- 2. TRUNC()함수 사용 : 날짜의 시간 부분을 제거하고 날짜만 반환
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TRUNC(DATE_OF_BIRTH) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL 
  AND GENDER = 'W' 
  AND TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
ORDER BY MEMBER_ID ASC;
